### ISSUE TITLE
Design Rust experiments

### ISSUE THREAD

**Issue by scotts** [IBM/sliding-window-aggregators#41]
Currently, the Rust implementations are using the [Criterion](https://github.com/bheisler/criterion.rs) crate to experimentally compare the implementations. I've spent some time with them, and done a deep-dive into Criterion itself. At the moment, my conclusion is that it doesn't quite meet our needs. My main concerns:

1. Criterion is exclusively a time-based benchmarking framework. What I mean by that is that users tell Criterion how long to run for. Since how long the experiments are run for is static, the workload itself is necessarily variable. The experiments we have used to assess the current SWAGs, and published, are vice-versa: we keep the workload static and allow the time they run to be variable. (In fact, how long they take is one of the main things we report.) The Criterion author makes a case that for microbenchmarks this is fine, and I agree that for most use cases it is. But for us, since we're simulating a streaming system, it's imperative that (say) we actually process 5 million elements, even if it takes 5 minutes. We get less information if we only process 83,000 elements in 5 seconds. We need to make sure we process enough elements so that we can correctly scale up our window sizes, and to make sure we fully exercise all parts of a SWAG. I find our requirements don't mesh with Criterion being a time-based benchmarking framework.
2. I have had difficulty generating the kinds of comparisons across the dimensions that I want (SWAG, window size).
3. Collecting and storing raw data does seem to be a priority of the framework. That's critical for eventually publishing the eperiments.
4. This is a minor point compared to the others, as I would negotiate with it if all of the above worked for our needs easily, but: I'm not comfortable that parts of the experiment are run in code outside of our control. When investigating performance over the years, have completely control over the full lifecycle of the program has benefited us in fully understanding various behavior that we see. When we control everything, we can be confident that differences in performance are from differences in the SWAGs and not experimental artifact. (As an example of the sort of thing we have done while investigating performance anomalies, see https://github.com/scotts/sliding-window-aggregators/blob/3b756f77baa340fa9f4b04a1ce486c4498f88292/cpp/src/data_benchmark.cc#L50-L54.)

The good news is that Rust makes writing our on benchmarks much simpler than C++! For example, my mess of template overloads in C++ can become a proper Rust macro, resulting in something much more understandable and extendable:

```
    query_run! {
        opts =>
            [[ReCalc, Sum, Max],
             [TwoStacks, Sum, Max],
             [Reactive, Sum, Max],
             [SoE, Sum]]
    }
```

See https://github.com/scotts/sliding-window-aggregators/blob/rust-exp/rust/benches/bench_static.rs for the Rust equivalent to https://github.com/scotts/sliding-window-aggregators/blob/rust-exp/cpp/src/benchmark_driver.cc. Note that the C++ benchmark driver includes a header file which has now also gotten out of hand.

I had hoped we could keep both the Criterion and by-hand benchmarks around at the same time, but I ran into difficulties with that approach. I ran into conflicts with options when using `cargo bench`.

@segeljakt, I'm interested to hear your thoughts.

**Comment by segeljakt** [comment]
@scotts I agree with your points, often I include Criterion in my projects because it is easy to setup and it does the statistical analysis for you. For more serious evaluation I think it is better to roll a custom benchmark suite. It should be possible to have both Criterion and custom benchmarks if we create a `cargo` workspace:

```
swag/
    Cargo.toml
    swag-core/
        Cargo.toml
        src/
        benches/
        tests/
    swag-criterion/
        Cargo.toml
        benches/
```

The code looks great. It is probably not needed, but I recently found out there is a function [`black_box`](https://doc.rust-lang.org/std/hint/fn.black_box.html) that can be used for hiding optimisation opportunities from Rust.

There are also some useful testing/profiling frameworks for finding bugs/bottlenecks:

* [`cargo-fuzz`](https://github.com/rust-fuzz/cargo-fuzz) (Fuzzing)
* [`coz-rs`](https://github.com/alexcrichton/coz-rs) (Causal profiling)
* [`flamegraph`](https://github.com/flamegraph-rs/flamegraph) (Profiling)
* [`iai`](https://github.com/bheisler/iai) (One-shot benchmarks)

I have recently been using `cargo-fuzz` in a project I'm working on. My memory is still fresh so I could help out integrating it if you want. It is great for finding workloads which causes the program to crash.
